
runtime: php
env: flex
service: backend

runtime_config:
  document_root: .

env_variables:
  FIREBASE_PROJECT_ID: 'upcash-md'


# api_version: 1
# threadsafe: true

# runtime: php55
# application: upcash-md
# service: backend

# handlers:
# - url: /users\.php
#   script: users.php

# - url: /investimentos/read\.php
#   script: investimentos/read.php

