# Arquivo yaml para deploy no Google Cloud Plataform
# App Engine Flex Environment

runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  FIREBASE_PROJECT_ID: 'tcc-nan'


# only for dev tests
# comment this lines for prod
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


# api_version: 1
# threadsafe: true

