runtime: php55
api_version: 1
threadsafe: true
service: backend

handlers:
- url: /users\.php
  script: users.php

- url: /investimentos/read\.php
  script: investimentos/read.php

env_variables:
  FIREBASE_PROJECT_ID: 'upcash-md'