
runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  FIREBASE_PROJECT_ID: 'upcash-md'


# only for dev tests
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


# api_version: 1
# threadsafe: true

# runtime: php55
# application: upcash-md
# service: backend

# handlers:
# - url: /users\.php
#   script: users.php

# - url: /investimentos/read\.php
#   script: investimentos/read.php

